######################################################################
# Automatically generated by qmake (3.1) Mon Dec 23 18:41:41 2019
######################################################################

QT += core gui testlib

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = testcryptutil
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Copy the "vectors" directory to the build directory
copyvectors.commands = $(COPY_DIR) \"$$shell_path($$PWD\\vectors)\" \"$$shell_path($$OUT_PWD\\vectors)\"
first.depends = $(first) copyvectors
export(first.depends)
export(copyvectors.commands)
QMAKE_EXTRA_TARGETS += first copyvectors

DEFINES += \
    SODIUM_STATIC

# Input
SOURCES += \
    ../../cryptutil.cpp \
    ../../identitymodel.cpp \
    ../../identityparser.cpp \
    ../../inc/bigint/BigInteger.cc \
    ../../inc/bigint/BigIntegerAlgorithms.cc \
    ../../inc/bigint/BigIntegerUtils.cc \
    ../../inc/bigint/BigUnsigned.cc \
    ../../inc/bigint/BigUnsignedInABase.cc \
    ../testutils.cpp \
    testcryptutil.cpp

HEADERS += \
    ../../cryptutil.h \
    ../../identitymodel.h \
    ../../identityparser.h \
    ../../inc/bigint/BigInteger.hh \
    ../../inc/bigint/BigIntegerAlgorithms.hh \
    ../../inc/bigint/BigIntegerLibrary.hh \
    ../../inc/bigint/BigIntegerUtils.hh \
    ../../inc/bigint/BigUnsigned.hh \
    ../../inc/bigint/BigUnsignedInABase.hh \
    ../../inc/bigint/NumberlikeArray.hh \
    ../testutils.h \
    testcryptutil.h

DISTFILES += \
    $$PWD/../../lib/sodium/lib/libsodium.lib \
    $$PWD/../../lib/sodium/lib/libsodium.so \
    $$PWD/../../lib/sodium/lib/libsodiumd.lib \
    vectors/enhash-vectors.txt \
    vectors/enscrypt-vectors.txt \
    vectors/identity-lock-vectors.txt \
    vectors/identity-vectors.txt \
    vectors/ins-vectors.txt

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../../lib/sodium/lib/ -llibsodium
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../../lib/sodium/lib/ -llibsodiumd
else:unix: LIBS += -L$$PWD/../../lib/sodium/lib/ -lsodium

INCLUDEPATH += $$PWD/../../lib/sodium/include
DEPENDPATH += $$PWD/../../lib/sodium/include

QMAKE_LFLAGS_WINDOWS += /NODEFAULTLIB:LIBCMTD \
    /NODEFAULTLIB:LIBCMT
